# Generated by Django 4.1.3 on 2022-12-05 16:34

from django.db import migrations, models
import manufacturing.models.products


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturing', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=manufacturing.models.products.upload_to),
        ),
    ]
